#!/usr/bin/env php
<?php
echo "Running tests.. ";
exec('vendor/bin/phpunit', $output, $returnCode);

if ($returnCode !== 0) {
  if (is_string($output)) {
    $output = [$output];
  }
  // Show full output
  echo PHP_EOL . implode($output, [PHP_EOL]) . PHP_EOL;
  echo "Cannot push changes untill tests are OK.." . PHP_EOL;
  exit(1);
}

// Show summary (last line)
echo array_pop($output) . PHP_EOL;

echo "Running code sniffer.. ";
exec('vendor/bin/phpcs', $output, $returnCode);

if ($returnCode !== 0) {
  if (is_string($output)) {
    $output = [$output];
  }
  // Show full output
  echo PHP_EOL . implode(PHP_EOL, $output) . PHP_EOL;
  echo "Cannot push changes until styles are OK.." . PHP_EOL;
  exit(1);
}
if (is_string($output)) {
  $output = [$output];
}
// Show summary (last line)
echo array_pop($output) . PHP_EOL;
exit(0);
