language: php

php:
  - 7.3
  - 7.4

install: composer install

before_script:
  - composer require php-coveralls/php-coveralls

script:
  - mkdir -p coverage
  - composer check

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then travis_retry php vendor/bin/php-coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.4' ]]; then travis_retry php vendor/bin/php-coveralls -v; fi